

# Defining Routing
spring: 
   application:
       name: CLOUD-API-GATEWAY
   cloud:
     gateway:
       discovery.locator:
        enabled: true
        lowerCaseServiceId: true
       routes:
       - id: welcome-api
         uri: lb://WELCOME-API
         predicates:
         - Path=/welcome
       - id: greet-api
         uri: lb://GREET-API    #lb- load balancing 
         predicates:
         - Path=/greet
        
server:
  port: 3366